[environment]
version = "0.3.0"

[repository]
name = "frqubit.tutoring.website"
version = "0.1.0"

[scripts]
reload_db = "batl frqubit.tutoring.database:reload_db"
dev = "concurrently 'batl frqubit.tutoring.backend:dev' 'pnpm dev'"

[dependencies]
"frqubit.tutoring.backend" = "0.1.0"
"battalion.source.github" = "0.1.0"

[links]
"frqubit.tutoring.backend/src/utils" = "src/lib/backend/utils"
"frqubit.tutoring.backend/src/modules" = "src/lib/backend/modules"

[restrict.Unix]
include = "require"

[[sources]]
handler = "battalion.source.github"
repository = "frqubit/tutoring_website"
